export const dummyData = {
    career: [
      { id: 1, option: 'Get a college degree', happiness: +20, intelligence: +50 },
      { id: 2, option: 'Start your own business',health: -30, happiness: +20},
      { id: 3, option: 'Join a corporate job',happiness: +20,intelligence: +20 },
      { id: 4, option: 'Pursue a creative career (artist, musician, writer)',happiness: +20,intelligence: +50 },
      { id: 5, option: 'Work in a non-profit organization',happiness: +20 },
      { id: 6, option: 'Become an entrepreneur',happiness: +20 },
      { id: 7, option: 'Join the military or civil service',happiness: +20 },
      { id: 8, option: 'Become a teacher or professor',happiness: +20 },
      { id: 9, option: 'Work in the healthcare industry', health: +30, intelligence: +20 },
      { id: 10, option: 'Pursue a trade or technical career',happiness: +20 },
    ],
    social: [
      { id: 1, option: 'Get married', happiness: +50 },
      { id: 2, option: 'Have children', happiness: +70 },
      { id: 3, option: 'Join a social club or organization' },
      { id: 4, option: 'Volunteer for a cause', happiness: +40 },
      { id: 5, option: 'Travel the world',happiness: +20,intelligence: +50},
      { id: 6, option: 'Attend cultural events or festivals',intelligence: +50 },
      { id: 7, option: 'Host parties or social gatherings', charisma: +30 },
      { id: 8, option: 'Participate in community service', happiness: +40 },
      { id: 9, option: 'Join a sports team or club' ,intelligence: +50,happiness: +20},
      { id: 10, option: 'Learn a new language' ,happiness: +20,intelligence: +50},
    ],
    finance: [
      { id: 1, option: 'Save for retirement', happiness: +20 },
      { id: 2, option: 'Invest in stocks or real estate', intelligence: +30 },
      { id: 3, option: 'Pay off debts',happiness: -20 },
      { id: 4, option: 'Start an emergency fund', happiness: +10 },
      { id: 5, option: 'Donate to charity', happiness: +30 },
      { id: 6, option: 'Create a budget and stick to it',intelligence: +50 },
      { id: 7, option: 'Invest in your education or skills', intelligence: +40 },
      { id: 8, option: 'Purchase insurance (life, health, etc.)', health: +20 },
      { id: 9, option: 'Plan for your children education' ,happiness: +20},
      { id: 10, option: 'Diversify your investment portfolio' ,intelligence: +50},
    ],
    activities: [
      { id: 1, option: 'Learn a new skill or hobby', intelligence: +20 },
      { id: 2, option: 'Practice a sport or physical activity', strength: +50 },
      { id: 3, option: 'Attend cultural events or festivals', happiness: +30 },
      { id: 4, option: 'Take up a creative pursuit (painting, music, writing)', happiness: +40 },
      { id: 5, option: 'Spend time with family and friends', happiness: +60, charisma: +20 },
      { id: 6, option: 'Travel to new places', happiness: +70 },
      { id: 7, option: 'Read books or listen to podcasts', intelligence: +30 },
      { id: 8, option: 'Participate in outdoor activities (hiking, camping, etc.)', strength: +40 },
      { id: 9, option: 'Take up gardening or home improvement projects' },
      { id: 10, option: 'Attend classes or workshops', intelligence: +40 },
    ],
  };
  